version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: 'GITPOD_MINIO_URL'
      MINIO_BROWSER_REDIRECT_URL: 'GITPOD_MINIO_CONSOLE_URL'
      MINIO_DEFAULT_BUCKETS: 'sample'
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local